spring:
  application:
    name: test_work
  profiles:
    active: dev
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/test_work
    username: myuser
    password: myuser
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/test_work
    username: myuser
    password: myuser
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update

